### ISSUE TITLE
假的吧，不公开就是不公开何必拿着changeformer说开源，直接把changeformer代码拿过来，就说借鉴，

### ISSUE THREAD

**Issue by lixue13** [LiLisaZhi/STADE-CDNet#6]

**Comment by LiLisaZhi** [comment]
你哪里有问题？

**Comment by LiLisaZhi** [comment]
请留下你的联系方式，如果你哪里有具体问题，我们可以详细聊。Please leave your contact information, if you have any specific questions, we can talk in detail.

**Comment by LiLisaZhi** [comment]
Please email with me as not often come here.

**Comment by LiLisaZhi** [comment]
> _No description provided._

你好，你哪里有问题，请邮件联系我，在第一个评论我的，他已经调通了。如果你有什么具体问题，我们可以邮件交流，因为我很忙，可能没有来的及看，但是邮件是会看的。谢谢您。

Hello, where do you have a problem？ Please contact me by email, in the first comment on me, he has been tuned. If you have any specific questions, we can exchange emails, because I am very busy, may not come and read, but the email will be read. Thank you very much.
